name: CI

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  check:
    name: Check
    if: |
      !contains(github.event.head_commit.message, '(skip ci)')
      && !contains(github.event.head_commit.message, '(skip ci/docs)')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Check
        run: cargo check --all-features
      - name: Cache for next jobs
        uses: actions/cache@v2
        with:
          key: ${{ github.run_id }}-target
          path: |
            ./target
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git

  test:
    name: Test
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Get cache
        uses: actions/cache@v2
        with:
          key: ${{ github.run_id }}-target
          path: |
            ./target
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
      - name: Test
        run: cargo test --all-features --no-fail-fast

  clippy:
    name: Clippy
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: clippy
      - name: Get cache
        uses: actions/cache@v2
        with:
          key: ${{ github.run_id }}-target
          path: |
            ./target
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings

  fmt:
    name: Fmt
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt
      - name: Get cache
        uses: actions/cache@v2
        with:
          key: ${{ github.run_id }}-target
          path: |
            ./target
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
      - name: Fmt
        run: cargo fmt -- --check
