name: Docs

on:
  push: { branches: [main] }

jobs:
  deploy:
    name: Deploy
    if: |
      !contains(github.event.head_commit.message, '(skip docs)')
      && !contains(github.event.head_commit.message, '(skip ci/docs)')
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      CARGO_NET_RETRY: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        run: |
          cargo doc --no-deps --all-features
          cp utils/redirect.html target/doc/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: docs
          publish_dir: ./target/doc
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Build docs:'
